GET http://localhost:3030/api/candidate/index?q=&skip=&limit= 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmExNzM2OWJjODk5NGQ1MDZhZmU0YWIiLCJpYXQiOjE2NTUyMTA0ODEsImV4cCI6MTY1NTIyMDQ4MX0.WPe5eGevT6QsGqAJosjFmtw-biGMMQOCcFaaXiycwKE 

###
GET https://cosmos.starhunterent.com/api/hello
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmExNzM2OWJjODk5NGQ1MDZhZmU0YWIiLCJpYXQiOjE2NTUyMTA0ODEsImV4cCI6MTY1NTIyMDQ4MX0.WPe5eGevT6QsGqAJosjFmtw-biGMMQOCcFaaXiycwKE 

###
PATCH  http://localhost:3030/api/candidate/total_points/62be54b1eeaa082c3804f6ea
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmExNzM2OWJjODk5NGQ1MDZhZmU0YWIiLCJpYXQiOjE2NTY2NDA0NDcsImV4cCI6MTY1NjY1MDQ0N30.MZkDIn2huh156haZviJrhNlWjv26EqjRqBYJnALwiQM

{
    "total_points":500
}
###
GET https://cosmos.starhunterent.com/api/candidate/topfive

###
GET http://localhost:3000/api/user/testMiddleWare
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmExNzM2OWJjODk5NGQ1MDZhZmU0YWIiLCJpYXQiOjE2NTUyMTA0ODEsImV4cCI6MTY1NTIyMDQ4MX0.WPe5eGevT6QsGqAJosjFmtw-biGMMQOCcFaaXiycwKE
###

GET https://cosmos.starhunterent.com/api/voteParameter/getVoteParams
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmExNzQzOGZkYTEwZDgzMjlhOGM3MTAiLCJpYXQiOjE2NTUyMDMzMzUsImV4cCI6MTY1NTIxMzMzNX0.7YT8ZK994J60ALVlygTBNWtIesf_D07rf73SzRwU2I4

###

POST http://localhost:3030/api/voteParameter/seed
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmM3ZDYxYWY3MTllMTIzYTZlOWFhNTQiLCJpYXQiOjE2NTcyNjgwMTYsImV4cCI6MTY1NzI3ODAxNn0.kJqk1p_7I5a1jlgYIfAUgCQNHr45ktp9CT6v0zwdFBU

{
    "isVoteOn": false,
    "cash": 1000,
    "token1": 101,
    "token2": 10,
    "point" : 50
}

###
GET https://cosmos.starhunterent.com/api/voteParameter/getVoteParams

###
PATCH  https://cosmos.starhunterent.com/api/voteParameter/setVoteON
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmExNzQzOGZkYTEwZDgzMjlhOGM3MTAiLCJpYXQiOjE2NTYzMjc4NzcsImV4cCI6MTY1NjMzNzg3N30.2Ex2oMSqZYD4B_suzJ-ruUXMNIZp9BLM79vb89HZad8
###
PATCH  https://cosmos.starhunterent.com/api/voteParameter/setVoteOFF
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmExNzQzOGZkYTEwZDgzMjlhOGM3MTAiLCJpYXQiOjE2NTYzMjc4NzcsImV4cCI6MTY1NjMzNzg3N30.2Ex2oMSqZYD4B_suzJ-ruUXMNIZp9BLM79vb89HZad8
###

GET https://cosmos.starhunterent.com/api/voteParameter/isVoteON
###

PATCH http://localhost:3030/api/voteParameter/setConversionRates
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmM3ZDYxYWY3MTllMTIzYTZlOWFhNTQiLCJpYXQiOjE2NTc1MTk0MTgsImV4cCI6MTY1NzUyOTQxOH0.dWEY-4hcfWEpXidUgO0UBiZzplw95V4Yz-5lCVl7tjY

{
    "cash": 1,
    "token1": 12,
    "token2": 30,
    "point" : 150
}
###

POST http://localhost:3030/api/user/login
content-type: application/json

{
    "username": "pree",
    "password": "1234"
}
###


POST http://localhost:3030/api/buyToken/add
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmM3ZDYxYWY3MTllMTIzYTZlOWFhNTQiLCJpYXQiOjE2NTcyNjgwMTYsImV4cCI6MTY1NzI3ODAxNn0.kJqk1p_7I5a1jlgYIfAUgCQNHr45ktp9CT6v0zwdFBU

{
    "token": 4000,
    "bonus": 400
}
###
GET https://cosmos.starhunterent.com/api/buyToken/index
###
GET http://localhost:3030/api/buyToken/show/62c7ef3d08503e685a0c602f
###
PATCH  http://localhost:3030/api/buyToken/edit/62c7ef3d08503e685a0c602f
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmM3ZDYxYWY3MTllMTIzYTZlOWFhNTQiLCJpYXQiOjE2NTcyNjgwMTYsImV4cCI6MTY1NzI3ODAxNn0.kJqk1p_7I5a1jlgYIfAUgCQNHr45ktp9CT6v0zwdFBU

{
    "token": 1200,
    "bonus": 20
}

###
DELETE  https://cosmos.starhunterent.com/api/buyToken/delete/62bbba562bdf2fa4ba248fb7
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjllMjAxY2Y4MDhmMDhkNjBiYzllY2QiLCJpYXQiOjE2NTY0NzAwMTIsImV4cCI6MTY1NjQ4MDAxMn0.jk0KKAV_846yMfFR-TuWM1Wz4pcr51UVxvFdrC-yUwo
###
GET http://localhost:3030/api/buyToken/totalTokens/62c7ef3d08503e685a0c602f

###
POST https://cosmos.starhunterent.com/api/sentGiftHistory/sendAndRecord
content-type: application/json

{
    "user_id": "62c6cf4f0771b93cb29f1e20",
    "candidate_id": "62a6a700ff9c10499b2145f0",
    "gift_id": "id-g-3",
    "send_date_time" : "2022-07-24T12:10:00+07:00",
    "token": 100,
    "username": "username225",
    "email": "preetiam@gmail.com"
}

###

GET https://cosmos.starhunterent.com/api/sentGiftHistory/index

###
POST https://vote.cosmos.starhunterent.com/clientapi/UpdateVoteLog
content-type: application/json
key : '95182f700496d6c0a27d3bef6e3e6dac'

{
    "userid" : "62c6cf4f0771b93cb29f1e20",
    "username": "iammrugesh",
    "email": "mrugeshpatelcumulative@gmail.com",
    "token": 10,
    "point": 50,
    "candidate": "62a6a78bff9c10499b2145f4"
}